//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Axe.Windows.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisplayStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Axe.Windows.Core.Resources.DisplayStrings", typeof(DisplayStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [l={0},t={1},w={2},h={3}].
        /// </summary>
        internal static string BoundingRectangleFormat {
            get {
                return ResourceManager.GetString("BoundingRectangleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal(1).
        /// </summary>
        internal static string HorizontalOrientation {
            get {
                return ResourceManager.GetString("HorizontalOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [l={0},t={1},r={2},b={3}].
        /// </summary>
        internal static string LeftTopRightBottomFormat {
            get {
                return ResourceManager.GetString("LeftTopRightBottomFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None(0).
        /// </summary>
        internal static string NoneOrientation {
            get {
                return ResourceManager.GetString("NoneOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [x={0},y={1}].
        /// </summary>
        internal static string PointFormat {
            get {
                return ResourceManager.GetString("PointFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown ({0}).
        /// </summary>
        internal static string UnknownFormat {
            get {
                return ResourceManager.GetString("UnknownFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical(2).
        /// </summary>
        internal static string VerticalOrientation {
            get {
                return ResourceManager.GetString("VerticalOrientation", resourceCulture);
            }
        }
    }
}
