//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxeWindowsCLI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisplayStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AxeWindowsCLI.Resources.DisplayStrings", typeof(DisplayStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid delay: {0}. Please enter an integer value from 0 to 60..
        /// </summary>
        internal static string ErrorInvalidDelayFormat {
            get {
                return ResourceManager.GetString("ErrorInvalidDelayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid verbosity level: {0}.
        /// </summary>
        internal static string ErrorInvalidVerbosityFormat {
            get {
                return ResourceManager.GetString("ErrorInvalidVerbosityFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found multiple processes with name {0}.
        /// </summary>
        internal static string ErrorMultipleMatchingProcessNameFormat {
            get {
                return ResourceManager.GetString("ErrorMultipleMatchingProcessNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find process with id {0}.
        /// </summary>
        internal static string ErrorNoMatchingProcessIdFormat {
            get {
                return ResourceManager.GetString("ErrorNoMatchingProcessIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find process with name {0}.
        /// </summary>
        internal static string ErrorNoMatchingProcessNameFormat {
            get {
                return ResourceManager.GetString("ErrorNoMatchingProcessNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify either processId or processName on the command line..
        /// </summary>
        internal static string ErrorNoTarget {
            get {
                return ResourceManager.GetString("ErrorNoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Potential Framework Issue: {0}.
        /// </summary>
        internal static string FrameworkIssueLink {
            get {
                return ResourceManager.GetString("FrameworkIssueLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {0} seconds before scan..
        /// </summary>
        internal static string ScanDelayCountdownMoreThanOneSecondLeft {
            get {
                return ResourceManager.GetString("ScanDelayCountdownMoreThanOneSecondLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   1 second before scan..
        /// </summary>
        internal static string ScanDelayCountdownOneSecondLeft {
            get {
                return ResourceManager.GetString("ScanDelayCountdownOneSecondLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delaying {0} seconds before scanning..
        /// </summary>
        internal static string ScanDelayHeaderMoreThanOneSecond {
            get {
                return ResourceManager.GetString("ScanDelayHeaderMoreThanOneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delaying second before scanning..
        /// </summary>
        internal static string ScanDelayHeaderOneSecond {
            get {
                return ResourceManager.GetString("ScanDelayHeaderOneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggering scan.
        /// </summary>
        internal static string ScanDelayTriggeringScan {
            get {
                return ResourceManager.GetString("ScanDelayTriggeringScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Id = {0}.
        /// </summary>
        internal static string ScanIdFormat {
            get {
                return ResourceManager.GetString("ScanIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following exception was caught: {0}.
        /// </summary>
        internal static string ScanNotCompleteExceptionFormat {
            get {
                return ResourceManager.GetString("ScanNotCompleteExceptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete. .
        /// </summary>
        internal static string ScanNotCompleteIntro {
            get {
                return ResourceManager.GetString("ScanNotCompleteIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No further data is available..
        /// </summary>
        internal static string ScanNotCompleteNoException {
            get {
                return ResourceManager.GetString("ScanNotCompleteNoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     {0}.
        /// </summary>
        internal static string ScanResultDetailElementPatternFormat {
            get {
                return ResourceManager.GetString("ScanResultDetailElementPatternFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Element Patterns:.
        /// </summary>
        internal static string ScanResultDetailElementPatternsHeader {
            get {
                return ResourceManager.GetString("ScanResultDetailElementPatternsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Element Properties:.
        /// </summary>
        internal static string ScanResultDetailElementPropertiesHeader {
            get {
                return ResourceManager.GetString("ScanResultDetailElementPropertiesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     {0} = {1}.
        /// </summary>
        internal static string ScanResultDetailElementPropertyFormat {
            get {
                return ResourceManager.GetString("ScanResultDetailElementPropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------------------------------------------------------------.
        /// </summary>
        internal static string ScanResultDetailFooter {
            get {
                return ResourceManager.GetString("ScanResultDetailFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0}: {1}.
        /// </summary>
        internal static string ScanResultDetailHeader {
            get {
                return ResourceManager.GetString("ScanResultDetailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results were written to \&quot;{0}\&quot;.
        /// </summary>
        internal static string ScanResultsLocationFormat {
            get {
                return ResourceManager.GetString("ScanResultsLocationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} errors were found.
        /// </summary>
        internal static string ScanResultsMultipleErrorsFormat {
            get {
                return ResourceManager.GetString("ScanResultsMultipleErrorsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 error was found.
        /// </summary>
        internal static string ScanResultsSingleError {
            get {
                return ResourceManager.GetString("ScanResultsSingleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Target:.
        /// </summary>
        internal static string ScanTargetIntro {
            get {
                return ResourceManager.GetString("ScanTargetIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Process ID = {0}.
        /// </summary>
        internal static string ScanTargetProcessIdFormat {
            get {
                return ResourceManager.GetString("ScanTargetProcessIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Process Name = {0}.
        /// </summary>
        internal static string ScanTargetProcessNameFormat {
            get {
                return ResourceManager.GetString("ScanTargetProcessNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string ScanTargetSeparator {
            get {
                return ResourceManager.GetString("ScanTargetSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Third Party Notices in default browser. If this fails, manually open \&quot;{0}\&quot;.
        /// </summary>
        internal static string ThirdPartyNoticeFormat {
            get {
                return ResourceManager.GetString("ThirdPartyNoticeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axe.Windows Accessibility Scanner CLI (version {0}).
        /// </summary>
        internal static string VersionFormat {
            get {
                return ResourceManager.GetString("VersionFormat", resourceCulture);
            }
        }
    }
}
