// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// This file was generated by a tool. Edits to this file will be lost the next time the file is generated
using System.Collections.Generic;
using static Axe.Windows.Core.Types.ControlType;

namespace Axe.Windows.Rules.Misc
{
    static class ControlTypeStrings
    {
        public static IReadOnlyDictionary<int, string> Dictionary;

#pragma warning disable CA1810
        static ControlTypeStrings()
        {
            var d = new Dictionary<int, string>
            {
                [UIA_AppBarControlTypeId] = "AppBar",
                [UIA_ButtonControlTypeId] = "Button",
                [UIA_CalendarControlTypeId] = "Calendar",
                [UIA_CheckBoxControlTypeId] = "CheckBox",
                [UIA_ComboBoxControlTypeId] = "ComboBox",
                [UIA_CustomControlTypeId] = "Custom",
                [UIA_DataGridControlTypeId] = "DataGrid",
                [UIA_DataItemControlTypeId] = "DataItem",
                [UIA_DocumentControlTypeId] = "Document",
                [UIA_EditControlTypeId] = "Edit",
                [UIA_GroupControlTypeId] = "Group",
                [UIA_HeaderControlTypeId] = "Header",
                [UIA_HeaderItemControlTypeId] = "HeaderItem",
                [UIA_HyperlinkControlTypeId] = "Hyperlink",
                [UIA_ImageControlTypeId] = "Image",
                [UIA_ListControlTypeId] = "List",
                [UIA_ListItemControlTypeId] = "ListItem",
                [UIA_MenuBarControlTypeId] = "MenuBar",
                [UIA_MenuControlTypeId] = "Menu",
                [UIA_MenuItemControlTypeId] = "MenuItem",
                [UIA_PaneControlTypeId] = "Pane",
                [UIA_ProgressBarControlTypeId] = "ProgressBar",
                [UIA_RadioButtonControlTypeId] = "RadioButton",
                [UIA_ScrollBarControlTypeId] = "ScrollBar",
                [UIA_SemanticZoomControlTypeId] = "SemanticZoom",
                [UIA_SeparatorControlTypeId] = "Separator",
                [UIA_SliderControlTypeId] = "Slider",
                [UIA_SpinnerControlTypeId] = "Spinner",
                [UIA_SplitButtonControlTypeId] = "SplitButton",
                [UIA_StatusBarControlTypeId] = "StatusBar",
                [UIA_TabControlTypeId] = "Tab",
                [UIA_TabItemControlTypeId] = "TabItem",
                [UIA_TableControlTypeId] = "Table",
                [UIA_TextControlTypeId] = "Text",
                [UIA_ThumbControlTypeId] = "Thumb",
                [UIA_TitleBarControlTypeId] = "TitleBar",
                [UIA_ToolBarControlTypeId] = "ToolBar",
                [UIA_ToolTipControlTypeId] = "ToolTip",
                [UIA_TreeControlTypeId] = "Tree",
                [UIA_TreeItemControlTypeId] = "TreeItem",
                [UIA_WindowControlTypeId] = "Window"
            };

            ControlTypeStrings.Dictionary = d;
        }
#pragma warning restore CA1810
    } // class
} // namespace
