//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Axe.Windows.Rules.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Axe.Windows.Rules.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element&apos;s HelpText property must not be null or white space.
        /// </summary>
        internal static string ElementHelpTextNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ElementHelpTextNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element&apos;s LocalizedControlType property must not be null or white space.
        /// </summary>
        internal static string ElementLocalizedControlTypeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ElementLocalizedControlTypeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element&apos;s Name property must not be null or white space.
        /// </summary>
        internal static string ElementNameNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ElementNameNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element&apos;s Parent property must not be null.
        /// </summary>
        internal static string ElementParentNull {
            get {
                return ResourceManager.GetString("ElementParentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected T to be an enumeration type.
        /// </summary>
        internal static string ExpectedEnumType {
            get {
                return ResourceManager.GetString("ExpectedEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected to find a valid ancestor element.
        /// </summary>
        internal static string ExpectedValidAncestor {
            get {
                return ResourceManager.GetString("ExpectedValidAncestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Condition.Context to be valid.
        /// </summary>
        internal static string ExpectedValidConditionContext {
            get {
                return ResourceManager.GetString("ExpectedValidConditionContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given int parameter must not be zero.
        /// </summary>
        internal static string IntParameterEqualsZero {
            get {
                return ResourceManager.GetString("IntParameterEqualsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int parameter must not be less than zero.
        /// </summary>
        internal static string IntParameterLessThanZero {
            get {
                return ResourceManager.GetString("IntParameterLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No control type entry was found in dictionary. Key value = {0}.
        /// </summary>
        internal static string NoControlTypeEntryFound {
            get {
                return ResourceManager.GetString("NoControlTypeEntryFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on the Rule.Condition match, there should have been at least one element found in the PassesTest method of {0}.
        /// </summary>
        internal static string NoElementFound {
            get {
                return ResourceManager.GetString("NoElementFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find potential LocalizedControlType string(s) for the given control type.
        /// </summary>
        internal static string NoLocalizedControlTypeStringFound {
            get {
                return ResourceManager.GetString("NoLocalizedControlTypeStringFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected the given string not to be null and not to be white space.
        /// </summary>
        internal static string StringNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("StringNullOrWhiteSpace", resourceCulture);
            }
        }
    }
}
