//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Axe.Windows.Automation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Axe.Windows.Automation.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must be a non-empty IEnumerable.
        /// </summary>
        internal static string NoDesktopElements {
            get {
                return ResourceManager.GetString("NoDesktopElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Actions property of the given ScanTools object should not be null.
        /// </summary>
        internal static string ScanToolsActionsNull {
            get {
                return ResourceManager.GetString("ScanToolsActionsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NativeMethods property of the given ScanTools object should not be null.
        /// </summary>
        internal static string ScanToolsNativeMethodsNull {
            get {
                return ResourceManager.GetString("ScanToolsNativeMethodsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OutputFileHelper property of the given ScanTools object should not be null.
        /// </summary>
        internal static string ScanToolsOutputFileHelperNull {
            get {
                return ResourceManager.GetString("ScanToolsOutputFileHelperNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ResultsAssembler property of the given ScanTools object should not be null.
        /// </summary>
        internal static string ScanToolsResultsAssemblerNull {
            get {
                return ResourceManager.GetString("ScanToolsResultsAssemblerNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TargetElementLocator property of the given ScanTools object should not be null.
        /// </summary>
        internal static string ScanToolsTargetElementLocatorNull {
            get {
                return ResourceManager.GetString("ScanToolsTargetElementLocatorNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given string must not be null or white space.
        /// </summary>
        internal static string StringNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("StringNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected the variable &apos;{0}&apos; not to be null.
        /// </summary>
        internal static string VariableNull {
            get {
                return ResourceManager.GetString("VariableNull", resourceCulture);
            }
        }
    }
}
